echo "=== Persistence Check ==="
grep -q "media-libs/libcamera" /var/lib/portage/world && echo "[PASS] libcamera in world file" || echo "[FAIL]"
[ -d /var/db/repos/local/media-libs/libcamera ] && echo "[PASS] Local overlay exists" || echo "[FAIL]"
[ -f /var/db/repos/local/media-libs/libcamera/files/libcamera-0.7.2-debayer-fixes.patch ] && echo "[PASS] Debayer patch in overlay" || echo "[FAIL]"
[ -f /var/db/repos/local/media-libs/libcamera/libcamera-0.7.2.ebuild ] && echo "[PASS] Ebuild in overlay" || echo "[FAIL]"
[ -f /var/db/repos/local/media-libs/libcamera/Manifest ] && echo "[PASS] Manifest exists" || echo "[FAIL]"
[ -f /usr/share/libcamera/ipa/simple/ov2740.yaml ] && echo "[PASS] Tuning file exists" || echo "[FAIL]"
[ -f /etc/init.d/ipu6-camera-init ] && echo "[PASS] Init script exists" || echo "[FAIL]"
grep -q "dev-python/ply" /var/db/repos/local/media-libs/libcamera/libcamera-0.7.2.ebuild && echo "[PASS] ply in BDEPEND" || echo "[FAIL]"
